export const CHARACTER_VECTORS: Record<string, { faction: string; traits: number[] }> = {
  // Format: [justice, power, social, emotion, world, identity, method, loyalty]
  'nakajima-atsushi':    { faction: 'agency',  traits: [6,5,6,8,8,6,5,7] },
  'dazai-osamu':         { faction: 'agency',  traits: [4,6,4,3,5,9,3,2] },
  'kunikida-doppo':      { faction: 'agency',  traits: [9,6,7,5,8,8,5,8] },
  'ranpo-edogawa':       { faction: 'agency',  traits: [7,2,5,2,7,6,2,5] },
  'akiko-yosano':        { faction: 'agency',  traits: [8,7,7,6,8,7,6,8] },
  'junichiro-tanizaki':  { faction: 'agency',  traits: [7,5,6,7,7,6,5,9] },
  'naomi-tanizaki':      { faction: 'agency',  traits: [5,4,5,8,6,5,4,9] },
  'kyouka-izumi':        { faction: 'agency',  traits: [7,7,5,7,7,7,6,8] },
  'kenji-miyazawa':      { faction: 'agency',  traits: [9,8,6,9,9,4,7,7] },
  'edgar-allan-poe':     { faction: 'guild',   traits: [6,4,2,6,5,5,2,4] },
  'nakahara-chuuya':     { faction: 'mafia',   traits: [5,9,7,7,4,4,8,9] },
  'akutagawa-ryunosuke': { faction: 'mafia',   traits: [3,9,4,8,2,3,8,7] },
  'ozaki-kouyou':        { faction: 'mafia',   traits: [5,7,8,4,4,6,5,7] },
  'gin-akutagawa':       { faction: 'mafia',   traits: [4,8,3,3,3,4,8,10] },
  'higuchi-ichiyo':      { faction: 'mafia',   traits: [6,3,4,9,6,5,4,10] },
  'tachihara-michizou':  { faction: 'mafia',   traits: [6,6,4,6,5,4,5,6] },
  'fitzgerald':          { faction: 'guild',   traits: [4,8,9,5,4,7,6,6] },
  'lucy-montgomery':     { faction: 'guild',   traits: [5,5,3,8,6,5,4,6] },
  'john-steinbeck':      { faction: 'guild',   traits: [7,7,5,6,7,6,5,7] },
  'herman-melville':     { faction: 'guild',   traits: [5,9,7,3,4,4,8,5] },
  'mark-twain':          { faction: 'guild',   traits: [6,6,5,5,6,7,4,5] },
  'louisa-may-alcott':   { faction: 'guild',   traits: [7,5,7,7,7,6,4,8] },
  'teruko-okura':        { faction: 'hunting_dogs', traits: [2,9,6,2,2,3,9,4] },
  'tetchou-suehiro':     { faction: 'hunting_dogs', traits: [8,8,6,3,5,4,8,9] },
  'jouno-saigiku':       { faction: 'hunting_dogs', traits: [6,7,5,4,4,6,3,6] },
  'minoura-motoji':      { faction: 'special_div',  traits: [8,2,5,6,7,6,4,8] },
  'alexander-pushkin':   { faction: 'rats',    traits: [2,6,3,2,2,5,2,3] },
  'ivan-goncharov':      { faction: 'rats',    traits: [4,9,3,5,4,5,8,5] },
  'sigma':               { faction: 'decay',   traits: [6,4,3,8,6,8,4,6] },
  'bram-stoker':         { faction: 'decay',   traits: [2,9,4,2,2,2,9,3] },
  'agatha-christie':     { faction: 'clock_tower', traits: [6,5,8,2,5,6,1,5] },
  'rudyard-kipling':     { faction: 'clock_tower', traits: [5,7,7,3,4,5,6,4] },
  'oscar-wilde':         { faction: 'clock_tower', traits: [6,5,5,6,6,8,3,6] },
}

export const RESERVED_SLUGS = new Set([
  'mori-ogai',
  'fukuzawa-yukichi',
  'fitzgerald',
  'fukuchi-ouchi',
  'fyodor-dostoevsky',
  'nikolai-gogol',
  'ango-sakaguchi',
  'sakunosuke-oda',
])

